title: Vinura's Blog
description: ~~~~~~~~~~~~~~~~~~~
# author:
#   name: Vinura (Dhananjaya) Galwaduge
#   email: vgalwadu@uwo.ca

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  syntax_highlighter: rouge


 #social_links:
  
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }